global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pulse-processor"
    static_configs:
      - targets: ["processor:5050"]
    metrics_path: /metrics

  - job_name: "pulse-ingestor"
    static_configs:
      - targets: ["ingestor:9100"]
    metrics_path: /metrics
